import { chromium } from 'playwright-core'
const b = await chromium.launch({ channel: 'chrome', headless: true })
const p = await b.newContext({ locale: 'ko-KR', viewport: { width: 1400, height: 1000 } }).then(c => c.newPage())
await p.goto('https://nhuf.molit.go.kr/FP/FP05/FP0502/FP05020701.jsp', { waitUntil: 'domcontentloaded', timeout: 45000 })
await p.waitForTimeout(5000)
await p.getByRole('link', { name: '청년전용 버팀목전세자금', exact: true }).first().click({ timeout: 20000 })
await p.waitForLoadState('domcontentloaded', { timeout: 45000 }).catch(() => {})
await p.waitForTimeout(7000)
console.log('제목: ' + (await p.title()))
console.log('주소: ' + p.url())
const t = await p.evaluate(() => document.body.innerText.replace(/[ \t]+/g, ' '))
const i = t.indexOf('대출금리')
console.log('--- 대출금리 구간 ---')
console.log(i > -1 ? t.slice(i, i + 700) : '(못 찾음)')
const j = t.indexOf('대출한도')
console.log('--- 대출한도 ---')
console.log(j > -1 ? t.slice(j, j + 220) : '(못 찾음)')
await b.close()
